accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # accounts/signup
    path('signup/', views.signup, name='signup'),

    # accounts/1/2/add_payment_method
    path('<int:accounts_pk>/<int:payment_pk>/add_payment_method/',
    views.add_payment_method,
    name='add_payment_method'
    ),

    # accounts/1/my_page
    path('<int:accounts_pk>/my_page/', views.my_page, name='my_page'),

    # accounts/insert_payment_info
    path('<int:accounts_pk>/modify_user_info', views.modify_user_info, name='modify_user_info'),

    # accounts/login
    path('login/', views.login, name='login'),

    # accounts/logout
    path('logout/', views.logout, name='logout'),
]

board/urls.py
from django.urls import path
from . import views
app_name = 'board'
urlpatterns = [
    path('', views.index, name='board_index'),
    path('<int:product_id>/product/', views.board_product, name='board_product'),
    path('product/create/', views.create_product, name='board_product_create'),
    path('product/delete/<int:product_id>', views.board_product_delete, name='board_product_delete'),
    path('product/modify/<int:product_id>', views.board_product_modify, name='board_product_modify'),
    path('product/create/<int:product_id>/comment/', views.board_comment_create, name='board_comment_create'),
    path('product/delete/<int:product_id>/<int:comment_id>/comment/', views.board_comment_delete, name='board_comment_delete'),

]

peaceful_secondary_kingdom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('board/', include('board.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 이미지 파일을 위한 url 설정

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    def __str__(self):
        return f'{self.username}'
    birthday = models.DateField(default='1990-01-01')
    address = models.TextField(null=True)


class PaymentInfo(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.DO_NOTHING,
        related_name='payment_info',
    )
    bank_account = models.IntegerField(null=True)
    bank_account_password = models.IntegerField(null=True)


'''
# 선택정보만 따로 뺀 것. (안씀)
class UserExtraInfo(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='user_extra_info',
    )
    birthday = models.DateField()
    address = models.TextField()
'''

accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import PaymentInfo

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username',
    )


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'first_name', 
            'last_name',
            'email',
            'birthday',
            'address',
        )


class PaymentInfoForm(forms.ModelForm):

    class Meta:
        model = PaymentInfo
        fields = '__all__'


class CustomPaymentChangeForm(UserChangeForm):

    class Meta:
        model = PaymentInfo
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe, require_http_methods
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as user_login, logout as user_logout
from django.contrib.auth.decorators import login_required
from .forms import (CustomUserCreationForm, PaymentInfoForm, CustomUserChangeForm, CustomPaymentChangeForm)
from .models import User, PaymentInfo
from django.http import HttpResponseForbidden


# Create your views here.
# accounts/signup
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form_user = CustomUserCreationForm(request.POST)
        if form_user.is_valid():
            user=form_user.save()
            form_payment = PaymentInfo.objects.create(user=user)
            form_payment.save()
            return redirect('board:board_index')
    else:
        form_user = CustomUserCreationForm()
    context = {
        'form_user' : form_user,
    }
    return render(request, 'accounts/signup.html', context)
        

@login_required
def add_payment_method(request):
    if request.method == 'POST':
        form = PaymentInfoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:my_page')
    else:
        form = PaymentInfoForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/add_payment_method.html', context)


@login_required
def modify_payment_method(request, payment_pk):
    payment = get_object_or_404(PaymentInfo, pk=payment_pk)
    if request.method == 'POST':
        form = PaymentInfoForm(request.POST, instance=payment)
        if form.is_valid():
            payment = form.save()
            return redirect('accounts:my_page')
    else:
        form = PaymentInfoForm()
    context = {'form' : form}
    return render(request, 'accounts/modify_user_info.html', context)



@login_required
def my_page(request, accounts_pk, payment_pk):
    user = get_object_or_404(User, pk=accounts_pk)
    if request.user != user:
        return HttpResponseForbidden()
    form_user = CustomUserChangeForm(request, request.POST)
    form_payment = CustomPaymentChangeForm(request, request.POST)
    context = {
        'form_user' : form_user,
        'form_payment' : form_payment,
    }
    return render(request, 'accounts/my_page.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def modify_user_info(request, accounts_pk):
    user_obj1 = get_object_or_404(User, pk=accounts_pk)
    if request.user != user_obj1.user:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user_obj1)
        if form.is_valid():
            user = form.save()
            return redirect('board:board_index')
    else: 
        user = CustomUserChangeForm(instance=user_obj1)
    context = {
        'user' : user,
    }
    return render(request, 'accounts/modify_user_info.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user_login(request, form.get_user())
            return redirect('board:board_index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)


@require_safe
def logout(request):
    user_logout(request)
    return redirect('board:board_index')

accounts/templates/accounts/add_payment_method.html
{% extends 'base.html' %}

{% block content %}

    


{% endblock content %}

accounts/templates/accounts/insert_payment_info.html
{% extends 'base.html' %}

{% block content %}

    <form action="{% url 'modify_user_info' accounts.pk %}">
        {% csrf_token %}
        {{ user.as_p }}
        {{ pay.as_p }}
        <button>수정</button>
    </form>



{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

    <h1>로그인</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>로그인</button>
    </form>


{% endblock content %}

accounts/templates/accounts/modify_user_info.html
{% extends 'base.html' %}

{% block content %}
    
    <form action="{% url 'modify_user_info' accounts.pk %}">
        {% csrf_token %}
        {{ user.as_p }}
        <button>수정</button>
    </form>



{% endblock content %}

accounts/templates/accounts/my_page.html
{% extends 'base.html' %}

{% block content %}

    <h1>마이 페이지</h1>

    <div>
        <a href="{% url 'accounts:modify_user_info' accounts.pk %}">
            <button>회원정보 수정</button>
        </a>
    </div>
    <div>
        <a href="{% url 'accounts:add_payment_method' %}">
            <button>결제정보 추가</button>
        </a>
    </div>
    <div>
        <a href="{% url 'accounts:add_payment_method' payment.pk %}">
            <button>결제정보 수정</button>
        </a>
    </div>
    <div>
        <a href="{% url 'accounts:add_payment_method' %}">
            <button>결제정보 삭제</button>
        </a>
    </div>


{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

    <h1>회원가입</h1>
    
    <form action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {{ form_user.as_p }}
        <div><button>계정 생성</button></div>
    </form>


{% endblock content %}